# Generated by Django 4.2.3 on 2023-07-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='input',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='online',
            name='user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
