# Generated by Django 4.2.3 on 2023-07-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_online_input_alter_online_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='online',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
