# Generated by Django 4.2.2 on 2023-07-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_alter_online_input_alter_online_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='language_name',
            field=models.CharField(choices=[('C', 'c'), ('CPP', 'cpp'), ('JAVA', 'java'), ('PYTHON', 'python')], max_length=10),
        ),
    ]
