# Generated by Django 4.2.2 on 2023-07-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_alter_online_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
