# Generated by Django 3.2.20 on 2023-08-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0007_online_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='questionDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
