# Generated by Django 3.2.20 on 2023-08-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0009_auto_20230825_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online',
            name='question',
        ),
        migrations.AddField(
            model_name='online',
            name='question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='online',
            name='language_name',
            field=models.IntegerField(choices=[(50, 'c'), (54, 'cpp'), (62, 'java'), (71, 'python')]),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
