# Generated by Django 3.2.20 on 2023-09-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0010_auto_20230831_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='Inputcase1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='online',
            name='Inputcase2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='online',
            name='Inputcase3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='online',
            name='Outputcase1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='online',
            name='Outputcase2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='online',
            name='Outputcase3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
